
export default {
  APP_TITLE: "Golden DC",
  HOME: "Home",
  CREATE_TEAM: "CREATE TEAM",
  START_MATCH: "START MATCH",
  START_MATCH_SMALL: "Start Match",
  SELECT_TEAM_SMALL: "Select Team",
  SQUAD_11: "Squad",
  MY_TEAMS: "My Teams",
  ADD_NEW_TEAM: "Add New Team",
  ADD_TEAM: "Add Team",
  TEAM_NAME: "Team Name",
  CITY: "City",
  TEAM_LOGO: "Team Logo",
  PLAYER_PHOTO: "Player Photo",
  PLAYER_NAME: "Player Name",
  PHONE_NUMBER: "Phone Number",
  ADD_PLAYER: "Add Player",
  ADD_PLAYER_CAPS: "ADD PLAYER",
  SELECT_PLAYING_SQUAD: "Select Playing Squad",
  NOT_NOW: "Not Now",
  NEXT: "Next",
  DONE: "Done",
  CAPTAIN_CAPS: "CAPTAIN",
  WICKET_KEEPER_CAPS: "WICKET KEEPER",
  NO_OF_OVERS: "No. of Overs",
  OVER_PER_BOWLER: "Over Per Bowler",
  GROUND_NAME:"Ground Name",
  DATE_TIME:"Date & Time",
  SCHEDULE_MATCH:"Schedule Match",
  TOSS:"Toss",
  WHO_WON_TOSS:"Who won the toss?",
  WINNER_TOSS:"Winner of the toss elected to?",
  VIRTUAL_TOSS:"VIRTUAL TOSS",
  LET_S_PLAY:"LET’S PLAY",
  BAT:"BAT",
  BATTING:"Batting",
  BOWL:"BOWL",
  BOWLING:"Bowling",
  START_INNINGS:"Start Innings",
  START_SCORING:"Start Scoring",
  SELECT_BOWLER:"Select Bowler",
  SELECT_BASTMAN:"Select Batsman",
  BOWLING_STYLE:"Bowling Style",
  WHAT_BOWLING_STYLE:"What the style of ",
  RIGHT_ARM_FAST:"Right-arm\nfast",
  RIGHT_ARM_MEDIUM:"Right-arm\nmedium",
  LEFT_ARM_FAST:"Left-arm\nfast",
  LEFT_ARM_MEDIUM:"Left-arm\nmedium",
  SLOW_LEFT_ARM_ORTHOBOX:"Slow left-arm\northodox",
  SLOW_LEFT_ARM_CHINA_MAN:"Slow left-arm\nchinaman",
  RIGHT_ARM_OFF_BREAK:"Right-arm Off\nBreak",
  RIGHT_ARM_LRG_BREAK:"Right-arm Lrg\nBreak",
  OK:"Ok",
  CANCEL:"Cancel",
  LIVE_MATCH:"Live Match",
  NO_TEAM:"No teams found",
  NO_PLAYER:"No player found",
}
